import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { useCart } from "@/contexts/CartContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { ShoppingBag, ArrowLeft, CheckCircle } from "lucide-react";
import type { User } from "@supabase/supabase-js";

const Checkout = () => {
  const { items, total, clearCart } = useCart();
  const navigate = useNavigate();
  const { toast } = useToast();
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState(false);
  const [form, setForm] = useState({
    name: "",
    phone: "",
    address: "",
    city: "",
    country: "Sénégal",
    notes: "",
    paymentMethod: "cash_on_delivery",
  });

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      setUser(session?.user ?? null);
      if (session?.user) {
        setForm((f) => ({
          ...f,
          name: session.user.user_metadata?.full_name || "",
        }));
      }
    });
  }, []);

  const formatPrice = (price: number) =>
    new Intl.NumberFormat("fr-FR", { style: "decimal" }).format(price) + " FCFA";

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (items.length === 0) return;
    if (!form.name || !form.phone || !form.address || !form.city) {
      toast({ title: "Erreur", description: "Veuillez remplir tous les champs obligatoires", variant: "destructive" });
      return;
    }

    setLoading(true);
    try {
      // Find the store from the first product
      const { data: product } = await supabase
        .from("products")
        .select("store_id")
        .eq("id", items[0].productId)
        .single();

      if (!product) throw new Error("Produit introuvable");

      // Create order - order_number is auto-generated by trigger
      const { data: order, error: orderError } = await supabase
        .from("orders")
        .insert({
          store_id: product.store_id,
          customer_id: user?.id || null,
          order_number: "TEMP", // Will be overridden by trigger
          subtotal: total,
          total: total,
          shipping_name: form.name,
          shipping_phone: form.phone,
          shipping_address: form.address,
          shipping_city: form.city,
          shipping_country: form.country,
          notes: form.notes || null,
          payment_method: form.paymentMethod,
          status: "pending",
          payment_status: "unpaid",
        })
        .select()
        .single();

      if (orderError) throw orderError;

      // Create order items
      const orderItems = items.map((item) => ({
        order_id: order.id,
        product_id: item.productId,
        variant_id: item.variantId || null,
        product_name: item.name,
        variant_name: item.variantName || null,
        quantity: item.quantity,
        unit_price: item.price,
        total: item.price * item.quantity,
      }));

      const { error: itemsError } = await supabase.from("order_items").insert(orderItems);
      if (itemsError) throw itemsError;

      clearCart();
      setSuccess(true);
    } catch (err: any) {
      toast({ title: "Erreur", description: err.message || "Erreur lors de la commande", variant: "destructive" });
    } finally {
      setLoading(false);
    }
  };

  if (success) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background px-4">
        <div className="text-center max-w-md">
          <CheckCircle className="w-16 h-16 text-primary mx-auto mb-4" />
          <h1 className="text-2xl font-bold text-foreground mb-2">Commande confirmée !</h1>
          <p className="text-muted-foreground mb-6">
            Merci pour votre commande. Vous recevrez une confirmation bientôt.
          </p>
          <Button variant="hero" onClick={() => navigate(-1)}>
            Continuer mes achats
          </Button>
        </div>
      </div>
    );
  }

  if (items.length === 0) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-background gap-4">
        <ShoppingBag className="w-16 h-16 text-muted-foreground" />
        <h1 className="text-xl font-semibold text-foreground">Votre panier est vide</h1>
        <Button onClick={() => navigate(-1)}>Retour</Button>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <header className="bg-card border-b border-border">
        <div className="container mx-auto flex items-center h-16 px-4 gap-3">
          <Button variant="ghost" size="icon" onClick={() => navigate(-1)}>
            <ArrowLeft className="w-5 h-5" />
          </Button>
          <h1 className="text-lg font-bold text-foreground">Finaliser la commande</h1>
        </div>
      </header>

      <main className="container mx-auto px-4 py-8">
        <div className="grid lg:grid-cols-5 gap-8">
          {/* Form */}
          <form onSubmit={handleSubmit} className="lg:col-span-3 space-y-6">
            <div className="bg-card rounded-xl border border-border p-6">
              <h2 className="font-semibold text-foreground mb-4">Informations de livraison</h2>
              <div className="grid sm:grid-cols-2 gap-4">
                <div>
                  <Label htmlFor="name">Nom complet *</Label>
                  <Input id="name" name="name" value={form.name} onChange={handleChange} required />
                </div>
                <div>
                  <Label htmlFor="phone">Téléphone *</Label>
                  <Input id="phone" name="phone" value={form.phone} onChange={handleChange} required />
                </div>
                <div className="sm:col-span-2">
                  <Label htmlFor="address">Adresse *</Label>
                  <Input id="address" name="address" value={form.address} onChange={handleChange} required />
                </div>
                <div>
                  <Label htmlFor="city">Ville *</Label>
                  <Input id="city" name="city" value={form.city} onChange={handleChange} required />
                </div>
                <div>
                  <Label htmlFor="country">Pays</Label>
                  <Input id="country" name="country" value={form.country} onChange={handleChange} />
                </div>
              </div>
            </div>

            <div className="bg-card rounded-xl border border-border p-6">
              <h2 className="font-semibold text-foreground mb-4">Mode de paiement</h2>
              <div className="space-y-3">
                {[
                  { value: "cash_on_delivery", label: "Paiement à la livraison" },
                  { value: "mobile_money", label: "Mobile Money (Orange Money, Wave...)" },
                  { value: "bank_transfer", label: "Virement bancaire" },
                ].map((m) => (
                  <label
                    key={m.value}
                    className={`flex items-center gap-3 p-3 rounded-lg border cursor-pointer transition-colors ${
                      form.paymentMethod === m.value ? "border-primary bg-primary/5" : "border-border"
                    }`}
                  >
                    <input
                      type="radio"
                      name="paymentMethod"
                      value={m.value}
                      checked={form.paymentMethod === m.value}
                      onChange={handleChange}
                      className="accent-primary"
                    />
                    <span className="text-sm font-medium text-foreground">{m.label}</span>
                  </label>
                ))}
              </div>
            </div>

            <div className="bg-card rounded-xl border border-border p-6">
              <Label htmlFor="notes">Notes (optionnel)</Label>
              <Input
                id="notes"
                name="notes"
                value={form.notes}
                onChange={handleChange}
                placeholder="Instructions de livraison..."
              />
            </div>

            <Button type="submit" variant="hero" size="xl" className="w-full" disabled={loading}>
              {loading ? "Traitement..." : `Confirmer la commande — ${formatPrice(total)}`}
            </Button>
          </form>

          {/* Summary */}
          <div className="lg:col-span-2">
            <div className="bg-card rounded-xl border border-border p-6 sticky top-20">
              <h2 className="font-semibold text-foreground mb-4">Résumé ({items.length} articles)</h2>
              <div className="space-y-3 mb-4">
                {items.map((item) => (
                  <div key={`${item.productId}-${item.variantId || ""}`} className="flex justify-between text-sm">
                    <div className="flex-1 min-w-0">
                      <p className="text-foreground truncate">{item.name}</p>
                      {item.variantName && (
                        <p className="text-xs text-muted-foreground">{item.variantName}</p>
                      )}
                      <p className="text-muted-foreground">x{item.quantity}</p>
                    </div>
                    <span className="font-medium text-foreground ml-2">
                      {formatPrice(item.price * item.quantity)}
                    </span>
                  </div>
                ))}
              </div>
              <div className="border-t border-border pt-3">
                <div className="flex justify-between font-semibold text-base">
                  <span>Total</span>
                  <span className="text-primary">{formatPrice(total)}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Checkout;
